/** Port of `Werewolf Node/Models/IPlayer.cs` `KillMthd`. */
export type KillMethod =
  | 'None'
  | 'Lynch'
  | 'Eat'
  | 'Shoot'
  | 'VisitWolf'
  | 'VisitVictim'
  | 'GuardWolf'
  | 'Detected'
  | 'Flee'
  | 'Hunt'
  | 'HunterShot'
  | 'LoverDied'
  | 'SerialKilled'
  | 'HunterCult'
  | 'GuardKiller'
  | 'VisitKiller'
  | 'Idle'
  | 'Suicide'
  | 'StealKiller'
  | 'Chemistry'
  | 'FallGrave'
  | 'Spotted'
  | 'Burn'
  | 'VisitBurning';
