/**
 * Port of `AchievementsReworked.cs` - the full catalog of 102 achievement codes, names, and
 * descriptions (English only; the original never localized these either). This module is
 * just the catalog - see `evaluate.ts` for which of these the evaluator can actually detect.
 */

export const ACHIEVEMENT_CODES = [
  'WelcomeToHell',
  'WelcomeToAsylum',
  'AlzheimerPatient',
  'OHAIDER',
  'SpyVsSpy',
  'Explorer',
  'Linguist',
  'NoIdeaWhat',
  'Enochlophobia',
  'Introvert',
  'Naughty',
  'Dedicated',
  'Obsessed',
  'HereJohnny',
  'GotYourBack',
  'Masochist',
  'Wobble',
  'Inconspicuous',
  'Survivalist',
  'BlackSheep',
  'Promiscuous',
  'MasonBrother',
  'DoubleShifter',
  'HeyManNiceShot',
  'DontStayHome',
  'DoubleVision',
  'DoubleKill',
  'ShouldHaveKnown',
  'LackOfTrust',
  'BloodyNight',
  'ChangingSides',
  'ForbiddenLove',
  'Developer',
  'FirstStone',
  'SmartGunner',
  'Streetwise',
  'OnlineDating',
  'BrokenClock',
  'SoClose',
  'CultCon',
  'SelfLoving',
  'ShouldveMentioned',
  'TannerOverkill',
  'SerialSamaritan',
  'CultFodder',
  'LoneWolf',
  'PackHunter',
  'GunnerSaves',
  'LongHaul',
  'OhShi',
  'Veteran',
  'NoSorcery',
  'CultistTracker',
  'ImNotDrunk',
  'WuffieCult',
  'DidYouGuardYourself',
  'SpoiledRichBrat',
  'ThreeLittleWolves',
  'President',
  'IHelped',
  'ItWasABusyNight',
  'StrongestAlpha',
  'AmIYourSeer',
  'DemotedByTheDeath',
  'WastedSilver',
  'Trustworthy',
  'DeepLove',
  'TimeToRetire',
  'SeeingBetweenTeams',
  'JustABeardyGuy',
  'ThatCameUnexpected',
  'NowImBlind',
  'EveryManForHimself',
  'MySweetieSoStrong',
  'CultLeader',
  'ThanksJunior',
  'DeathVillage',
  'ILostMyWisdom',
  'Affectionate',
  'LuckyDay',
  'ConditionRed',
  'Indestructible',
  'PsychopathKiller',
  'TodaysSpecial',
  'RomeoAndJuliet',
  'ReallyBadLuck',
  'Domino',
  'DoubleShot',
  'PlayingWithTheFire',
  'Firework',
  'ColdAsIce',
  'GoodChoiceForYou',
  'IncreaseThePack',
  'Firefighter',
  'HelpfulParanoia',
  'STierHunter',
  'TripleKill',
  'ResistTheBeast',
  'AtLeastYouTried',
  'LuckyNight',
  'InTheMiddleOfTheTrouble',
  'AmIHallucinating',
] as const;

export type AchievementCode = (typeof ACHIEVEMENT_CODES)[number];

export interface AchievementMeta {
  code: AchievementCode;
  order: number;
  name: string;
  description: string;
}

export const ACHIEVEMENTS: Record<AchievementCode, AchievementMeta> = {
  WelcomeToHell: {
    code: 'WelcomeToHell',
    order: 1,
    name: 'Welcome to Hell',
    description: 'Play a game',
  },
  WelcomeToAsylum: {
    code: 'WelcomeToAsylum',
    order: 2,
    name: 'Welcome to the Asylum',
    description: 'Play a chaos game',
  },
  AlzheimerPatient: {
    code: 'AlzheimerPatient',
    order: 3,
    name: "Alzheimer's Patient",
    description: 'Play a game with an amnesia language pack',
  },
  OHAIDER: {
    code: 'OHAIDER',
    order: 4,
    name: 'O HAI DER!',
    description: "Play a game with Para's secret account (not @para949)",
  },
  SpyVsSpy: {
    code: 'SpyVsSpy',
    order: 5,
    name: 'Spy vs Spy',
    description: 'Play a game in secret mode (no role reveal)',
  },
  Explorer: {
    code: 'Explorer',
    order: 6,
    name: 'Explorer',
    description: 'Play at least 2 games each in 10 different groups',
  },
  Linguist: {
    code: 'Linguist',
    order: 7,
    name: 'Linguist',
    description: 'Play at least 2 games each in 10 different language packs',
  },
  NoIdeaWhat: {
    code: 'NoIdeaWhat',
    order: 8,
    name: "I Have No Idea What I'm Doing",
    description: 'Play a game in secret amnesia mode',
  },
  Enochlophobia: {
    code: 'Enochlophobia',
    order: 9,
    name: 'Enochlophobia',
    description: 'Play a 35 player game',
  },
  Introvert: {
    code: 'Introvert',
    order: 10,
    name: 'Introvert',
    description: 'Play a 5 player game',
  },
  Naughty: {
    code: 'Naughty',
    order: 11,
    name: 'Naughty!',
    description: 'Play a game using any NSFW language pack',
  },
  Dedicated: { code: 'Dedicated', order: 12, name: 'Dedicated', description: 'Play 100 games' },
  Obsessed: { code: 'Obsessed', order: 13, name: 'Obsessed', description: 'Play 1000 games' },
  HereJohnny: {
    code: 'HereJohnny',
    order: 14,
    name: "Here's Johnny!",
    description: 'Get 50 kills as the serial killer',
  },
  GotYourBack: {
    code: 'GotYourBack',
    order: 15,
    name: "I've Got Your Back",
    description: 'Save 50 people as the Guardian Angel',
  },
  Masochist: {
    code: 'Masochist',
    order: 16,
    name: 'Masochist',
    description: 'Win a game as the Tanner',
  },
  Wobble: {
    code: 'Wobble',
    order: 17,
    name: 'Wobble Wobble',
    description: 'Survive a game as the drunk (at least 10 players)',
  },
  Inconspicuous: {
    code: 'Inconspicuous',
    order: 18,
    name: 'Inconspicuous',
    description:
      'In a game of 20 or more people, do not get a single lynch vote against you (and survive)',
  },
  Survivalist: {
    code: 'Survivalist',
    order: 19,
    name: 'Survivalist',
    description: 'Survive 100 games',
  },
  BlackSheep: {
    code: 'BlackSheep',
    order: 20,
    name: 'Black Sheep',
    description: 'Get lynched first 3 games in a row',
  },
  Promiscuous: {
    code: 'Promiscuous',
    order: 21,
    name: 'Promiscuous',
    description:
      'As the harlot, survive a 5+ night game without staying home or visiting the same person more than once',
  },
  MasonBrother: {
    code: 'MasonBrother',
    order: 22,
    name: 'Mason Brother',
    description: 'Be one of at least two surviving masons in a game',
  },
  DoubleShifter: {
    code: 'DoubleShifter',
    order: 23,
    name: 'Double Shifter',
    description: 'Change roles twice in one game (cult conversion does not count)',
  },
  HeyManNiceShot: {
    code: 'HeyManNiceShot',
    order: 24,
    name: 'Hey Man, Nice Shot',
    description: 'As the hunter, use your dying shot to kill a wolf or serial killer',
  },
  DontStayHome: {
    code: 'DontStayHome',
    order: 25,
    name: "That's Why You Don't Stay Home",
    description: 'As a wolf or cultist, kill or convert a harlot that stayed home',
  },
  DoubleVision: {
    code: 'DoubleVision',
    order: 26,
    name: 'Double Vision',
    description: 'Be one of two seers at the same time',
  },
  DoubleKill: {
    code: 'DoubleKill',
    order: 27,
    name: 'Double Kill',
    description: 'Be part of the Serial Killer / Hunter ending',
  },
  ShouldHaveKnown: {
    code: 'ShouldHaveKnown',
    order: 28,
    name: 'Should Have Known',
    description: 'As the Seer, reveal the Beholder',
  },
  LackOfTrust: {
    code: 'LackOfTrust',
    order: 29,
    name: 'I See a Lack of Trust',
    description: 'As the Seer, get lynched on the first day',
  },
  BloodyNight: {
    code: 'BloodyNight',
    order: 30,
    name: 'Sunday Bloody Sunday',
    description: 'Be one of at least 4 victims to die in a single night',
  },
  ChangingSides: {
    code: 'ChangingSides',
    order: 31,
    name: 'Change Sides Works',
    description: 'Change roles in a game, and win',
  },
  ForbiddenLove: {
    code: 'ForbiddenLove',
    order: 32,
    name: 'Forbidden Love',
    description: 'Win as a wolf / villager couple (villager, not village team)',
  },
  Developer: {
    code: 'Developer',
    order: 33,
    name: 'Developer',
    description: 'Have a pull request merged into the repo',
  },
  FirstStone: {
    code: 'FirstStone',
    order: 34,
    name: 'The First Stone',
    description: 'Be the first to cast a lynch vote 5 times in a single game',
  },
  SmartGunner: {
    code: 'SmartGunner',
    order: 35,
    name: 'Smart Gunner',
    description: 'As the Gunner, both of your bullets hit a wolf, serial killer, or cultist',
  },
  Streetwise: {
    code: 'Streetwise',
    order: 36,
    name: 'Streetwise',
    description:
      'Find a different wolf, serial killer, arsonist, or cultist 4 nights in a row as the detective',
  },
  OnlineDating: {
    code: 'OnlineDating',
    order: 37,
    name: 'Speed Dating',
    description: 'Have the bot select you as a lover (cupid failed to choose)',
  },
  BrokenClock: {
    code: 'BrokenClock',
    order: 38,
    name: 'Even a Stopped Clock is Right Twice a Day',
    description: 'As the Fool, have at least two of your visions be correct by the end of the game',
  },
  SoClose: {
    code: 'SoClose',
    order: 39,
    name: 'So Close!',
    description: 'As the Tanner, be tied for the most lynch votes',
  },
  CultCon: {
    code: 'CultCon',
    order: 40,
    name: 'Cultist Convention',
    description: 'Be one of 10 or more cultists alive at the end of a game',
  },
  SelfLoving: {
    code: 'SelfLoving',
    order: 41,
    name: 'Self Loving',
    description: 'As cupid, pick yourself as one of the lovers',
  },
  ShouldveMentioned: {
    code: 'ShouldveMentioned',
    order: 42,
    name: "Should've Said Something",
    description: 'As a wolf, your pack eats your lover (first night does not count)',
  },
  TannerOverkill: {
    code: 'TannerOverkill',
    order: 43,
    name: 'Tanner Overkill',
    description: 'As the Tanner, have everyone (but yourself) vote to lynch you',
  },
  SerialSamaritan: {
    code: 'SerialSamaritan',
    order: 44,
    name: 'Serial Samaritan',
    description: 'As the Serial Killer, kill at least 3 wolves in single game',
  },
  CultFodder: {
    code: 'CultFodder',
    order: 45,
    name: 'Cultist Fodder',
    description: 'Be the cultist that is sent to attempt to convert the Cult Hunter',
  },
  LoneWolf: {
    code: 'LoneWolf',
    order: 46,
    name: 'Lone Wolf',
    description: 'In a chaos game of 10 or more people, be the only wolf - and win',
  },
  PackHunter: {
    code: 'PackHunter',
    order: 47,
    name: 'Pack Hunter',
    description: 'Be one of 7 living wolves at one time',
  },
  GunnerSaves: {
    code: 'GunnerSaves',
    order: 48,
    name: 'Saved by the Bull(et)',
    description:
      'As a villager, the wolves match the number of villagers, but the game does not end because the gunner has a bullet',
  },
  LongHaul: {
    code: 'LongHaul',
    order: 49,
    name: 'In for the Long Haul',
    description: 'Survive for at least an hour in a single game',
  },
  OhShi: {
    code: 'OhShi',
    order: 50,
    name: 'OH SHI-',
    description: 'Kill your lover on the first night',
  },
  Veteran: {
    code: 'Veteran',
    order: 51,
    name: 'Veteran',
    description: 'Play 500 games.  You can now join @werewolfvets',
  },
  NoSorcery: {
    code: 'NoSorcery',
    order: 52,
    name: 'No Sorcery!',
    description: 'As a wolf, kill your sorcerer',
  },
  CultistTracker: {
    code: 'CultistTracker',
    order: 53,
    name: 'Cultist Tracker',
    description: 'As the cultist hunter, kill at least 3 cultists in one game',
  },
  ImNotDrunk: {
    code: 'ImNotDrunk',
    order: 54,
    name: "I'M NOT DRUN-- *BURPPP*",
    description: 'As the clumsy guy, have at least 3 correct lynches by the end of the game',
  },
  WuffieCult: {
    code: 'WuffieCult',
    order: 55,
    name: 'Wuffie-Cult',
    description: 'As the alpha wolf, successfully convert at least 3 victims into wolves',
  },
  DidYouGuardYourself: {
    code: 'DidYouGuardYourself',
    order: 56,
    name: 'Did you guard yourself?',
    description: 'As the guardian angel, survive after 3 tries guarding an unattacked wolf',
  },
  SpoiledRichBrat: {
    code: 'SpoiledRichBrat',
    order: 57,
    name: 'Spoiled Rich Brat',
    description: 'As the prince, still gets lynched even after revealing your identity',
  },
  ThreeLittleWolves: {
    code: 'ThreeLittleWolves',
    order: 58,
    name: 'Three Little Wolves and a Big Bad Pig',
    description: 'As the sorcerer, survive a game with three or more alive wolves',
  },
  President: {
    code: 'President',
    order: 59,
    name: 'President',
    description: 'As the mayor, successfully cast 3 lynch votes after revealing',
  },
  IHelped: {
    code: 'IHelped',
    order: 60,
    name: 'I Helped!',
    description: 'As a wolf cub, the alive pack has 2 successful eat attempts after you die',
  },
  ItWasABusyNight: {
    code: 'ItWasABusyNight',
    order: 61,
    name: 'It Was a Busy Night!',
    description: 'During the same night, got visited by 3 or more different visiting roles',
  },
  StrongestAlpha: {
    code: 'StrongestAlpha',
    order: 62,
    name: 'Strongest Alpha',
    description: 'As the alpha wolf, successfully infect the serial killer!',
  },
  AmIYourSeer: {
    code: 'AmIYourSeer',
    order: 63,
    name: 'Am I Your Seer?',
    description: 'As the fool, correctly spot the beholder',
  },
  DemotedByTheDeath: {
    code: 'DemotedByTheDeath',
    order: 64,
    name: 'Demoted by the Death',
    description:
      'As the hunter, shoot the wise elder with your final shot and die as lowly villager',
  },
  WastedSilver: {
    code: 'WastedSilver',
    order: 65,
    name: 'Wasted Silver',
    description: 'As the blacksmith, spread your silver dust the same day that the sandman sings',
  },
  Trustworthy: {
    code: 'Trustworthy',
    order: 66,
    name: 'Trustworthy!',
    description: 'As the wolf man, survive and win the game after being checked by seer',
  },
  DeepLove: {
    code: 'DeepLove',
    order: 67,
    name: 'Deep Love',
    description: 'As the doppelgänger, choose your lover as role model. What a deep love <3',
  },
  TimeToRetire: {
    code: 'TimeToRetire',
    order: 68,
    name: 'Time to retire...',
    description: 'As the sorcerer, be the last person alive in the village and lose the game',
  },
  SeeingBetweenTeams: {
    code: 'SeeingBetweenTeams',
    order: 69,
    name: 'Seeing between Teams',
    description: 'Be in a seer/sorcerer couple',
  },
  JustABeardyGuy: {
    code: 'JustABeardyGuy',
    order: 70,
    name: 'Just a Beardy Guy..?',
    description:
      'As the wolf man, be infected by the alpha wolf and become a real werewolf. AWOOOOOOO!',
  },
  ThatCameUnexpected: {
    code: 'ThatCameUnexpected',
    order: 71,
    name: 'That Came Unexpected!',
    description: 'As tanner, be lynched and win the game when there are only 3 persons left',
  },
  NowImBlind: {
    code: 'NowImBlind',
    order: 72,
    name: "Now I'm Blind",
    description: 'As the oracle, fail to get a vision because everyone else has the same role.',
  },
  EveryManForHimself: {
    code: 'EveryManForHimself',
    order: 73,
    name: 'Every Man for Himself!',
    description:
      'As the pacifist, save yourself from being lynched (at least 50% of votes have been cast for you already)',
  },
  MySweetieSoStrong: {
    code: 'MySweetieSoStrong',
    order: 74,
    name: 'My Sweetie so Strong!',
    description:
      'Be in love with the pacifist, and get saved from being lynched by them (at least 50% of votes have been cast for you already)',
  },
  CultLeader: {
    code: 'CultLeader',
    order: 75,
    name: 'Cult Leader',
    description: 'Be a cultist from the beginning of the game, survive and win.',
  },
  ThanksJunior: {
    code: 'ThanksJunior',
    order: 76,
    name: 'Thanks, Junior!',
    description:
      'After the wolf pack ate the Drunk, you turn into a wolf and can try to eat someone while the rest of the wolf pack is drunk!',
  },
  DeathVillage: {
    code: 'DeathVillage',
    order: 77,
    name: 'Death Village',
    description: 'Participate in a game that has no winner.',
  },
  ILostMyWisdom: {
    code: 'ILostMyWisdom',
    order: 78,
    name: 'I Lost my Wisdom',
    description: "As the wise elder, change your role! Suddenly you're not that wise anymore...",
  },
  Affectionate: {
    code: 'Affectionate',
    order: 79,
    name: 'Affectionate',
    description: 'As the harlot, visit your lover!',
  },
  LuckyDay: {
    code: 'LuckyDay',
    order: 80,
    name: 'Lucky Day',
    description: 'As the Alpha Wolf, infect the drunk and stay sober! Phew...',
  },
  ConditionRed: {
    code: 'ConditionRed',
    order: 81,
    name: 'Condition Red!',
    description: 'As the last wolf alive, eat the traitor. Oh no!',
  },
  Indestructible: {
    code: 'Indestructible',
    order: 82,
    name: 'Indestructible',
    description: 'Become Doppelgänger or Wild Child with your role model being yourself!',
  },
  PsychopathKiller: {
    code: 'PsychopathKiller',
    order: 83,
    name: 'Psychopath Killer',
    description: 'As the serial killer, win a game with 35 players!',
  },
  TodaysSpecial: {
    code: 'TodaysSpecial',
    order: 84,
    name: "Today's Special!",
    description:
      "Take part in a special werewolf event! Currently: Be fooled on April Fool's 2020!",
  },
  RomeoAndJuliet: {
    code: 'RomeoAndJuliet',
    order: 85,
    name: 'Romeo and Juliet',
    description: 'Be in love with the tanner, and win by lynching your lover!',
  },
  ReallyBadLuck: {
    code: 'ReallyBadLuck',
    order: 86,
    name: 'Really bad luck',
    description:
      'As a serial killer, stumble in a grave, then kill someone randomly and get fought off by the guardian angel.',
  },
  Domino: {
    code: 'Domino',
    order: 87,
    name: 'Domino',
    description: 'As a hunter, shoot another hunter causing them to shoot as well.',
  },
  DoubleShot: {
    code: 'DoubleShot',
    order: 88,
    name: 'Double Shot',
    description:
      'As the hunter or the gunner, shoot a bad role who is in love with another bad role!',
  },
  PlayingWithTheFire: {
    code: 'PlayingWithTheFire',
    order: 89,
    name: 'Playing with the Fire',
    description: 'As the arsonist, burn 5 or more houses in one night.',
  },
  Firework: {
    code: 'Firework',
    order: 90,
    name: 'Firework',
    description: 'As the arsonist, burn 10 or more houses in one night! What a nice firework :)',
  },
  ColdAsIce: {
    code: 'ColdAsIce',
    order: 91,
    name: 'Cold as Ice',
    description: 'As the Snow Wolf, freeze the harlot. Their love is cold as ice.',
  },
  GoodChoiceForYou: {
    code: 'GoodChoiceForYou',
    order: 92,
    name: 'Good Choice... For You',
    description: 'As the chemist, visit a player and survive 3 times in a single game.',
  },
  IncreaseThePack: {
    code: 'IncreaseThePack',
    order: 93,
    name: 'Increase the Pack!',
    description: 'After the wolf cub died, infect 2 players as the alpha wolf!',
  },
  Firefighter: {
    code: 'Firefighter',
    order: 94,
    name: 'Firefighter',
    description: 'As the guardian angel, clean three houses of kerosene.',
  },
  HelpfulParanoia: {
    code: 'HelpfulParanoia',
    order: 95,
    name: 'Helpful Paranoia',
    description: 'As the hunter, shoot two attackers!',
  },
  STierHunter: {
    code: 'STierHunter',
    order: 96,
    name: 'S-Tier Hunter',
    description: 'As the hunter, take down a wolf and a cultist in the same night!',
  },
  TripleKill: {
    code: 'TripleKill',
    order: 97,
    name: 'Triple Kill',
    description:
      'As a serial killer or wolf, have at least three people die by your hand in the same night!',
  },
  ResistTheBeast: {
    code: 'ResistTheBeast',
    order: 98,
    name: 'Resist the Beast',
    description:
      'As a trio of wild child, traitor, and cursed, all remain human and win the game with the village.',
  },
  AtLeastYouTried: {
    code: 'AtLeastYouTried',
    order: 99,
    name: 'At least you tried...',
    description:
      "As the guardian angel, save someone at night only to watch them die to the chemist's poison.",
  },
  LuckyNight: {
    code: 'LuckyNight',
    order: 100,
    name: 'Lucky Night',
    description: "Survive the chemist's visit and enjoy the harlot's visit in the same night!",
  },
  InTheMiddleOfTheTrouble: {
    code: 'InTheMiddleOfTheTrouble',
    order: 101,
    name: 'In the Middle of the Trouble',
    description: 'As the guardian angel, save a werewolf from an attack and survive!',
  },
  AmIHallucinating: {
    code: 'AmIHallucinating',
    order: 102,
    name: 'Am I hallucinating?!',
    description: 'As the fool, see a role which the seer can never see',
  },
};
